### ISSUE TITLE
Dock - Tokens not displaying new currencies

### ISSUE THREAD

**Issue by craftycowcat** [joev/SVUI-Temp#22] opened 2016-09-20 08:31 UTC
Can you look into the dock - tokens not displaying the currencies of Legion?

**Comment by drveoj** [comment] 2016-09-20 15:09
Have you downloaded my latest changes? I believe this is working:

**Comment by drveoj** [comment] 2016-09-20 22:49
Dupe of #3

**Closed as completed by drveoj** 2016-09-20 22:49 UTC
Labels: duplicate
