### ISSUE TITLE
Demon Hunter Metamorphosis

### ISSUE THREAD

**Issue by Mazgrael** [joev/SVUI-Temp#65] opened 2016-10-01 08:21 UTC
Missing buff info from both Unit Frames and Aura area near the mini-map.

**Comment by drveoj** [comment] 2016-10-01 09:15
Duplicate of #39 - I'll work this one out soon. Need to add in lots of bits from DH as SVUI is really pre-Legion :)

**Closed as completed by drveoj** 2016-10-01 09:15 UTC
Labels: duplicate

**Comment by Mazgrael** [comment] 2016-10-01 11:10
Brilliant :)
